# -*- coding: utf-8 -*-
"""deep_recommender_streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fuaCAvssliL_QS5AXWl69sQ3IsID70ZJ
"""

import re
import os
import random
import numpy as np
import pandas as pd
import streamlit as st
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.metrics import roc_auc_score, accuracy_score


# =========================
# 1. CONFIG
# =========================
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

st.set_page_config(page_title="Deep Learning Product Recommender", layout="wide")



# =========================
# 2. HELPERS (UPDATED)
# =========================
@st.cache_data
def load_csv(path):
    return pd.read_csv(path)
def clean_text(x):
    if pd.isna(x):
        return ""
    x = str(x).lower().strip()
    x = re.sub(r"[^\w\s]+", " ", x)
    x = re.sub(r"\s+", " ", x)
    return x

def clean_currency_to_numeric(series):
    """Xóa bỏ các ký tự lạ (đ, ., ,) và chuyển về số"""
    cleaned = series.astype(str).str.replace(r'[^\d]', '', regex=True)
    return pd.to_numeric(cleaned, errors='coerce').fillna(0)

def parse_discount(x):
    if pd.isna(x):
        return 0.0
    x = str(x)
    match = re.search(r"(\d+(\.\d+)?)", x)
    if match:
        return float(match.group(1))
    return 0.0





# =========================
# 3. PREPROCESS PRODUCT DATA (UPDATED)
# =========================
def preprocess_products(df):
    df = df.copy()
    df.columns = df.columns.str.strip()

    required_cols = [
        "platform", "keyword", "name", "brand", "price", "original_price",
        "discount", "rating", "review_count", "seller", "location",
        "item_id", "product_url", "image_url"
    ]

    for col in required_cols:
        if col not in df.columns:
            df[col] = np.nan

    # Tạo item_index đúng theo vị trí dòng
    df = df.reset_index().rename(columns={"index": "item_index"})

    # Làm sạch văn bản và lọc bỏ sản phẩm rác (tên quá ngắn hoặc là "0")
    df = df[df['name'].apply(lambda x: len(str(x)) > 5)].copy()
    text_cols = ["platform", "keyword", "name", "brand", "seller", "location"]
    for col in text_cols:
        df[col] = df[col].fillna("").apply(clean_text)

    # CHỈNH SỬA CHÍNH: Xử lý số liệu thực tế
    df["price"] = clean_currency_to_numeric(df["price"])
    df["original_price"] = clean_currency_to_numeric(df["original_price"])
    
    # Xử lý Rating (Tách số từ chuỗi "4.5/5")
    df["rating"] = df["rating"].astype(str).str.extract(r'(\d+\.?\d*)').astype(float).fillna(0)
    df["review_count"] = clean_currency_to_numeric(df["review_count"])
    df["discount_value"] = df["discount"].apply(parse_discount)

    # Logic xử lý giá 0.0
    missing_price_mask = df["price"] <= 0
    df.loc[missing_price_mask, "price"] = df.loc[missing_price_mask, "original_price"]
    
    # Điền giá trung vị nếu vẫn còn giá bằng 0 (Median Imputation)
    overall_median = df[df['price'] > 0]['price'].median()
    # Kiểm tra xem có cột brand không để tính median theo brand
    brand_median = df[df['price'] > 0].groupby('brand')['price'].transform('median')
    df.loc[df['price'] == 0, 'price'] = brand_median.fillna(overall_median)

    for col in ["name", "brand", "platform", "seller", "location", "product_url", "image_url"]:
        df[col] = df[col].fillna("")

    return df
# =========================
# 4. PREPROCESS USERS + INTERACTIONS
# =========================
def preprocess_users(users_df):
    users_df = users_df.copy()
    users_df.columns = users_df.columns.str.strip()

    if "user_id" not in users_df.columns:
        raise ValueError("synthetic_users.csv phải có cột user_id")

    if "user_name" not in users_df.columns:
        users_df["user_name"] = users_df["user_id"].apply(lambda x: f"user_{x}")

    return users_df


def preprocess_interactions(inter_df):
    inter_df = inter_df.copy()
    inter_df.columns = inter_df.columns.str.strip()

    if "item_index" not in inter_df.columns:
        if "item_id" in inter_df.columns:
            inter_df = inter_df.rename(columns={"item_id": "item_index"})
        else:
            raise ValueError("File interaction phải có cột item_index hoặc item_id")

    required_cols = ["user_id", "item_index", "interaction"]
    for col in required_cols:
        if col not in inter_df.columns:
            raise ValueError(f"File interaction thiếu cột: {col}")

    inter_df["user_id"] = pd.to_numeric(inter_df["user_id"], errors="coerce")
    inter_df["item_index"] = pd.to_numeric(inter_df["item_index"], errors="coerce")
    inter_df["interaction"] = pd.to_numeric(inter_df["interaction"], errors="coerce")

    inter_df = inter_df.dropna(subset=["user_id", "item_index", "interaction"]).copy()

    inter_df["user_id"] = inter_df["user_id"].astype(int)
    inter_df["item_index"] = inter_df["item_index"].astype(int)
    inter_df["interaction"] = inter_df["interaction"].astype(int)

    return inter_df


# =========================
# 5. BUILD TRAIN DATA
# =========================
def build_training_table(products_df, users_df, inter_df):
    data = inter_df.merge(products_df, on="item_index", how="left")
    data = data.merge(users_df, on="user_id", how="left")
    data = data.dropna(subset=["name"]).reset_index(drop=True)
    return data


def encode_features(data_df):
    df = data_df.copy()

    user_encoder = LabelEncoder()
    item_encoder = LabelEncoder()
    brand_encoder = LabelEncoder()
    platform_encoder = LabelEncoder()

    df["user_encoded"] = user_encoder.fit_transform(df["user_id"])
    df["item_encoded"] = item_encoder.fit_transform(df["item_index"])
    df["brand_encoded"] = brand_encoder.fit_transform(df["brand"].astype(str))
    df["platform_encoded"] = platform_encoder.fit_transform(df["platform"].astype(str))

    numeric_cols = ["price", "rating", "review_count", "discount_value"]
    scaler = MinMaxScaler()
    df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

    meta = {
        "user_encoder": user_encoder,
        "item_encoder": item_encoder,
        "brand_encoder": brand_encoder,
        "platform_encoder": platform_encoder,
        "scaler": scaler,
        "numeric_cols": numeric_cols
    }

    return df, meta


def make_model_inputs(df):
    return {
        "user_input": df["user_encoded"].values,
        "item_input": df["item_encoded"].values,
        "brand_input": df["brand_encoded"].values,
        "platform_input": df["platform_encoded"].values,
        "numeric_input": df[["price", "rating", "review_count", "discount_value"]].values.astype("float32")
    }


# =========================
# 6. MODEL
# =========================
def build_model(num_users, num_items, num_brands, num_platforms, embed_dim=32):
    user_input = tf.keras.layers.Input(shape=(1,), name="user_input")
    item_input = tf.keras.layers.Input(shape=(1,), name="item_input")
    brand_input = tf.keras.layers.Input(shape=(1,), name="brand_input")
    platform_input = tf.keras.layers.Input(shape=(1,), name="platform_input")
    numeric_input = tf.keras.layers.Input(shape=(4,), name="numeric_input")

    user_emb = tf.keras.layers.Embedding(num_users, embed_dim)(user_input)
    item_emb = tf.keras.layers.Embedding(num_items, embed_dim)(item_input)
    brand_emb = tf.keras.layers.Embedding(num_brands, 8)(brand_input)
    platform_emb = tf.keras.layers.Embedding(num_platforms, 8)(platform_input)

    user_vec = tf.keras.layers.Flatten()(user_emb)
    item_vec = tf.keras.layers.Flatten()(item_emb)
    brand_vec = tf.keras.layers.Flatten()(brand_emb)
    platform_vec = tf.keras.layers.Flatten()(platform_emb)

    dot_ui = tf.keras.layers.Dot(axes=1)([user_vec, item_vec])

    x = tf.keras.layers.Concatenate()([
        user_vec,
        item_vec,
        brand_vec,
        platform_vec,
        numeric_input,
        dot_ui
    ])

    x = tf.keras.layers.Dense(128, activation="relu")(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.30)(x)

    x = tf.keras.layers.Dense(64, activation="relu")(x)
    x = tf.keras.layers.BatchNormalization()(x)
    x = tf.keras.layers.Dropout(0.25)(x)

    x = tf.keras.layers.Dense(32, activation="relu")(x)
    output = tf.keras.layers.Dense(1, activation="sigmoid")(x)

    model = tf.keras.Model(
        inputs=[user_input, item_input, brand_input, platform_input, numeric_input],
        outputs=output
    )

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
        loss="binary_crossentropy",
        metrics=[
            tf.keras.metrics.BinaryAccuracy(name="accuracy"),
            tf.keras.metrics.AUC(name="auc")
        ]
    )

    return model


# =========================
# 7. TOP-K EVALUATION
# =========================
def evaluate_topk(artifacts, test_df, k=10, max_users=100):
    model = artifacts["model"]
    products_df = artifacts["products_df"]
    inter_df = artifacts["inter_df"]
    meta = artifacts["meta"]

    user_encoder = meta["user_encoder"]
    item_encoder = meta["item_encoder"]
    brand_encoder = meta["brand_encoder"]
    platform_encoder = meta["platform_encoder"]
    scaler = meta["scaler"]
    numeric_cols = meta["numeric_cols"]

    user_positive_test = (
        test_df[test_df["interaction"] == 1]
        .groupby("user_id")["item_index"]
        .apply(set)
        .to_dict()
    )

    all_users = list(user_positive_test.keys())
    if len(all_users) == 0:
        return {
            "precision_at_k": 0.0,
            "recall_at_k": 0.0,
            "hit_rate_at_k": 0.0,
            "evaluated_users": 0
        }

    if len(all_users) > max_users:
        rng = np.random.RandomState(SEED)
        all_users = list(rng.choice(all_users, size=max_users, replace=False))

    precisions = []
    recalls = []
    hits = []

    known_items = set(item_encoder.classes_)

    for user_id in all_users:
        true_items = user_positive_test.get(user_id, set())
        if len(true_items) == 0:
            continue

        seen_items = set(inter_df.loc[inter_df["user_id"] == user_id, "item_index"].tolist())

        candidate_df = products_df[products_df["item_index"].isin(known_items)].copy()
        candidate_df = candidate_df[~candidate_df["item_index"].isin(seen_items)].copy()

        add_back_df = products_df[products_df["item_index"].isin(true_items)].copy()
        candidate_df = pd.concat([candidate_df, add_back_df], ignore_index=True)
        candidate_df = candidate_df.drop_duplicates(subset=["item_index"]).copy()

        if candidate_df.empty:
            continue

        try:
            user_encoded = user_encoder.transform([user_id])[0]
        except Exception:
            continue

        candidate_df["user_encoded"] = user_encoded
        candidate_df["item_encoded"] = item_encoder.transform(candidate_df["item_index"])

        candidate_df["brand_safe"] = candidate_df["brand"].astype(str).apply(
            lambda x: x if x in brand_encoder.classes_ else brand_encoder.classes_[0]
        )
        candidate_df["platform_safe"] = candidate_df["platform"].astype(str).apply(
            lambda x: x if x in platform_encoder.classes_ else platform_encoder.classes_[0]
        )

        candidate_df["brand_encoded"] = brand_encoder.transform(candidate_df["brand_safe"])
        candidate_df["platform_encoded"] = platform_encoder.transform(candidate_df["platform_safe"])

        candidate_df[numeric_cols] = scaler.transform(candidate_df[numeric_cols])

        inputs = {
            "user_input": candidate_df["user_encoded"].values,
            "item_input": candidate_df["item_encoded"].values,
            "brand_input": candidate_df["brand_encoded"].values,
            "platform_input": candidate_df["platform_encoded"].values,
            "numeric_input": candidate_df[numeric_cols].values.astype("float32")
        }

        scores = model.predict(inputs, verbose=0).ravel()
        candidate_df["score"] = scores

        topk_items = set(
            candidate_df.sort_values("score", ascending=False)
            .head(k)["item_index"]
            .tolist()
        )

        hit_count = len(topk_items & true_items)

        precision = hit_count / k
        recall = hit_count / len(true_items)
        hit = 1.0 if hit_count > 0 else 0.0

        precisions.append(precision)
        recalls.append(recall)
        hits.append(hit)

    if len(precisions) == 0:
        return {
            "precision_at_k": 0.0,
            "recall_at_k": 0.0,
            "hit_rate_at_k": 0.0,
            "evaluated_users": 0
        }

    return {
        "precision_at_k": float(np.mean(precisions)),
        "recall_at_k": float(np.mean(recalls)),
        "hit_rate_at_k": float(np.mean(hits)),
        "evaluated_users": int(len(precisions))
    }


# =========================
# 8. TRAIN
# =========================
@st.cache_resource(show_spinner=False)
def train_model_cached(products_path, users_path, interactions_path, epochs, batch_size, embed_dim, eval_k):
    products_df = load_csv(products_path)
    users_df = load_csv(users_path)
    inter_df = load_csv(interactions_path)

    products_df = preprocess_products(products_df)
    users_df = preprocess_users(users_df)
    inter_df = preprocess_interactions(inter_df)

    data = build_training_table(products_df, users_df, inter_df)
    data_encoded, meta = encode_features(data)

    train_df, test_df = train_test_split(
        data_encoded,
        test_size=0.2,
        random_state=SEED,
        stratify=data_encoded["interaction"]
    )

    model = build_model(
        num_users=data_encoded["user_encoded"].nunique(),
        num_items=data_encoded["item_encoded"].nunique(),
        num_brands=data_encoded["brand_encoded"].nunique(),
        num_platforms=data_encoded["platform_encoded"].nunique(),
        embed_dim=embed_dim
    )

    train_inputs = make_model_inputs(train_df)
    test_inputs = make_model_inputs(test_df)

    callbacks = [
        tf.keras.callbacks.EarlyStopping(
            monitor="val_auc",
            mode="max",
            patience=3,
            restore_best_weights=True
        )
    ]

    history = model.fit(
        train_inputs,
        train_df["interaction"].values,
        validation_data=(test_inputs, test_df["interaction"].values),
        epochs=epochs,
        batch_size=batch_size,
        verbose=0,
        callbacks=callbacks
    )

    preds = model.predict(test_inputs, verbose=0).ravel()
    pred_labels = (preds >= 0.5).astype(int)

    metrics = {
        "test_auc": float(roc_auc_score(test_df["interaction"].values, preds)),
        "test_accuracy": float(accuracy_score(test_df["interaction"].values, pred_labels)),
        "train_rows": int(len(train_df)),
        "test_rows": int(len(test_df)),
    }

    topk_metrics = evaluate_topk(
        artifacts={
            "model": model,
            "products_df": products_df,
            "inter_df": inter_df,
            "meta": meta
        },
        test_df=test_df,
        k=eval_k,
        max_users=100
    )

    metrics.update(topk_metrics)

    artifacts = {
        "model": model,
        "products_df": products_df,
        "users_df": users_df,
        "inter_df": inter_df,
        "data_encoded": data_encoded,
        "train_df": train_df,
        "test_df": test_df,
        "meta": meta,
        "history": history.history,
        "metrics": metrics
    }

    return artifacts


# =========================
# 9. RECOMMENDATION
# =========================
def recommend_for_user(user_id, artifacts, top_k=10, exclude_seen=True):
    model = artifacts["model"]
    products_df = artifacts["products_df"]
    data_encoded = artifacts["data_encoded"]
    inter_df = artifacts["inter_df"]
    meta = artifacts["meta"]

    user_encoder = meta["user_encoder"]
    item_encoder = meta["item_encoder"]
    brand_encoder = meta["brand_encoder"]
    platform_encoder = meta["platform_encoder"]
    scaler = meta["scaler"]
    numeric_cols = meta["numeric_cols"]

    if user_id not in set(data_encoded["user_id"].unique()):
        return pd.DataFrame()

    user_encoded = user_encoder.transform([user_id])[0]
    candidate_df = products_df.copy()

    if exclude_seen:
        seen_items = set(inter_df.loc[inter_df["user_id"] == user_id, "item_index"].tolist())
        candidate_df = candidate_df[~candidate_df["item_index"].isin(seen_items)].copy()

    known_items = set(item_encoder.classes_)
    candidate_df = candidate_df[candidate_df["item_index"].isin(known_items)].copy()

    if candidate_df.empty:
        return pd.DataFrame()

    # --- PHẦN SỬA LỖI Ở ĐÂY ---
    # 1. Tạo bản sao để Scale (dùng cho model), KHÔNG ghi đè lên candidate_df
    numeric_scaled = scaler.transform(candidate_df[numeric_cols])
    
    candidate_df["user_encoded"] = user_encoded
    candidate_df["item_encoded"] = item_encoder.transform(candidate_df["item_index"])
    
    # Xử lý brand/platform an toàn
    candidate_df["brand_safe"] = candidate_df["brand"].astype(str).apply(
        lambda x: x if x in brand_encoder.classes_ else brand_encoder.classes_[0]
    )
    candidate_df["platform_safe"] = candidate_df["platform"].astype(str).apply(
        lambda x: x if x in platform_encoder.classes_ else platform_encoder.classes_[0]
    )
    
    candidate_df["brand_encoded"] = brand_encoder.transform(candidate_df["brand_safe"])
    candidate_df["platform_encoded"] = platform_encoder.transform(candidate_df["platform_safe"])

    # 2. Truyền numeric_scaled (dữ liệu 0-1) vào model thay vì candidate_df[numeric_cols]
    inputs = {
        "user_input": candidate_df["user_encoded"].values,
        "item_input": candidate_df["item_encoded"].values,
        "brand_input": candidate_df["brand_encoded"].values,
        "platform_input": candidate_df["platform_encoded"].values,
        "numeric_input": numeric_scaled.astype("float32") # Dùng bản đã scale
    }

    scores = model.predict(inputs, verbose=0).ravel()
    candidate_df["score"] = scores

    # 3. Kết quả trả về lúc này vẫn giữ nguyên Price, Rating gốc (chưa bị scale)
    result_cols = [
        "item_index", "name", "brand", "price", "rating",
        "review_count", "discount_value", "platform", "seller",
        "product_url", "image_url", "score"
    ]

    recs = candidate_df.sort_values("score", ascending=False).head(top_k)[result_cols].copy()
    return recs.reset_index(drop=True)


def get_user_history(user_id, artifacts, top_n=10):
    inter_df = artifacts["inter_df"]
    products_df = artifacts["products_df"]

    history_df = inter_df[inter_df["user_id"] == user_id].copy()
    history_df = history_df[history_df["interaction"] == 1]

    history_df = history_df.merge(products_df, on="item_index", how="left")
    history_df = history_df[[
        "item_index", "name", "brand", "price", "rating",
        "review_count", "platform", "seller"
    ]].head(top_n)

    return history_df.reset_index(drop=True)


# =========================
# 10. UI
# =========================
st.title("Deep Learning Product Recommender")
st.caption("Gợi ý sản phẩm bằng Neural Collaborative Filtering + Product Features")

st.sidebar.header("Cấu hình dữ liệu")
products_path = st.sidebar.text_input("Đường dẫn data_final_cleaned.csv", value="data_final_cleaned.csv")
users_path = st.sidebar.text_input("Đường dẫn synthetic_users.csv", value="synthetic_users.csv")
interactions_path = st.sidebar.text_input("Đường dẫn synthetic_interactions.csv", value="synthetic_interactions.csv")

st.sidebar.header("Cấu hình train")
epochs = st.sidebar.slider("Epochs", 3, 30, 8, 1)
batch_size = st.sidebar.selectbox("Batch size", [64, 128, 256, 512], index=1)
embed_dim = st.sidebar.selectbox("Embedding dim", [16, 32, 64], index=1)
top_k = st.sidebar.slider("Top K gợi ý", 5, 30, 10, 1)
eval_k = st.sidebar.slider("K để đánh giá Top-K", 3, 20, 10, 1)
exclude_seen = st.sidebar.checkbox("Ẩn sản phẩm đã tương tác", value=True)

missing_files = [p for p in [products_path, users_path, interactions_path] if not os.path.exists(p)]
if missing_files:
    st.error(f"Không tìm thấy file: {missing_files}")
    st.stop()

if st.button("Huấn luyện mô hình"):
    with st.spinner("Đang train mô hình deep learning..."):
        artifacts = train_model_cached(
            products_path=products_path,
            users_path=users_path,
            interactions_path=interactions_path,
            epochs=epochs,
            batch_size=batch_size,
            embed_dim=embed_dim,
            eval_k=eval_k
        )
    st.session_state["artifacts"] = artifacts
    st.success("Train xong mô hình.")

if "artifacts" not in st.session_state:
    st.info("Bấm 'Huấn luyện mô hình' để bắt đầu.")
    st.stop()

artifacts = st.session_state["artifacts"]
users_df = artifacts["users_df"]
metrics = artifacts["metrics"]
history = artifacts["history"]

st.subheader("Thông tin mô hình")
col1, col2, col3, col4 = st.columns(4)
col1.metric("Train rows", metrics["train_rows"])
col2.metric("Test rows", metrics["test_rows"])
col3.metric("Test Accuracy", f"{metrics['test_accuracy']:.4f}")
col4.metric("Test AUC", f"{metrics['test_auc']:.4f}")

col5, col6, col7, col8 = st.columns(4)
col5.metric(f"Precision@{eval_k}", f"{metrics.get('precision_at_k', 0):.4f}")
col6.metric(f"Recall@{eval_k}", f"{metrics.get('recall_at_k', 0):.4f}")
col7.metric(f"Hit Rate@{eval_k}", f"{metrics.get('hit_rate_at_k', 0):.4f}")
col8.metric("Evaluated Users", metrics.get("evaluated_users", 0))

with st.expander("Loss / Metric history"):
    hist_df = pd.DataFrame(history)
    st.dataframe(hist_df, use_container_width=True)

st.markdown("---")
st.subheader("Chọn người dùng để gợi ý")

user_options = users_df[["user_id", "user_name"]].copy()
user_options["display"] = user_options["user_name"].astype(str) + " (id=" + user_options["user_id"].astype(str) + ")"

selected_display = st.selectbox("Chọn user", user_options["display"].tolist())

selected_row = user_options[user_options["display"] == selected_display].iloc[0]
selected_user_id = int(selected_row["user_id"])
selected_user_name = selected_row["user_name"]

st.write(f"**User được chọn:** {selected_user_name} | `user_id = {selected_user_id}`")

col_left, col_right = st.columns([1, 2])

with col_left:
    st.markdown("### Lịch sử tương tác dương")
    history_df = get_user_history(selected_user_id, artifacts, top_n=10)
    if history_df.empty:
        st.warning("User này chưa có lịch sử tương tác dương.")
    else:
        st.dataframe(history_df, use_container_width=True)

with col_right:
    st.markdown("### Top sản phẩm gợi ý")
    recs = recommend_for_user(
        user_id=selected_user_id,
        artifacts=artifacts,
        top_k=top_k,
        exclude_seen=exclude_seen
    )

    if recs.empty:
        st.warning("Không có sản phẩm để gợi ý.")
    else:
        display_recs = recs.copy()
        display_recs["score"] = display_recs["score"].round(4)
        display_recs["price"] = display_recs["price"].round(0)
        display_recs["rating"] = display_recs["rating"].round(2)
        display_recs["review_count"] = display_recs["review_count"].round(0)
        display_recs["discount_value"] = display_recs["discount_value"].round(2)

        st.dataframe(display_recs, use_container_width=True)

        st.markdown("### Chi tiết từng sản phẩm")
        for _, row in display_recs.iterrows():
            with st.container():
                c1, c2 = st.columns([1, 4])

                with c1:
                    if str(row["image_url"]).strip():
                        st.image(row["image_url"], width=120)
                    else:
                        st.write("No image")

                with c2:
                    st.markdown(f"**{row['name']}**")
                    st.write(f"Brand: {row['brand']}")
                    st.write(f"Platform: {row['platform']}")
                    st.write(f"Seller: {row['seller']}")
                    st.write(f"Price: {row['price']}")
                    st.write(f"Rating: {row['rating']} | Reviews: {row['review_count']}")
                    st.write(f"Discount: {row['discount_value']}")
                    st.write(f"Predicted score: {row['score']}")
                    if str(row["product_url"]).strip():
                        st.markdown(f"[Xem sản phẩm]({row['product_url']})")

                st.markdown("---")

st.markdown("---")
st.subheader("Xem dữ liệu mẫu")

with st.expander("Users"):
    st.dataframe(artifacts["users_df"].head(10), use_container_width=True)

with st.expander("Products"):
    st.dataframe(artifacts["products_df"].head(10), use_container_width=True)

with st.expander("Interactions"):
    st.dataframe(artifacts["inter_df"].head(10), use_container_width=True)

st.markdown("---")
st.subheader("Cách chạy")
st.code(
    "pip install streamlit pandas numpy scikit-learn tensorflow\n"
    "streamlit run deep_recommender_streamlit_app.py",
    language="bash"
)